<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_QTYDescription1Sauce Labs Backpackcarry_2ba614</name>
   <tag></tag>
   <elementGuidId>4c759b1e-5eb4-4b5d-8825-800cce22c95d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='checkout_summary_container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkout_summary_container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e60625c8-8679-4562-a246-6ee67a6be8f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkout_summary_container</value>
      <webElementGuid>5cdf9d0f-9108-44e0-8315-5087267cb09b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkout_summary_container</value>
      <webElementGuid>d8e554f3-9478-4a4b-9e8b-f878cdf992b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>checkout-summary-container</value>
      <webElementGuid>1f94f292-98af-4635-a74b-9e716b09d0b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>QTYDescription1Sauce Labs Backpackcarry.allTheThings() with the sleek, streamlined Sly Pack that melds uncompromising style with unequaled laptop and tablet protection.$29.991Sauce Labs Fleece JacketIt's not every day that you come across a midweight quarter-zip fleece jacket capable of handling everything from a relaxing day outdoors to a busy day at the office.$49.99Payment Information:SauceCard #31337Shipping Information:Free Pony Express Delivery!Price TotalItem total: $79.98Tax: $6.40Total: $86.38CancelFinish</value>
      <webElementGuid>691b59d8-19d6-444b-a472-45a0cd956c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout_summary_container&quot;)</value>
      <webElementGuid>35cc5a88-44e3-4efd-9437-162b0656d5fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='checkout_summary_container']</value>
      <webElementGuid>555f68f0-77c5-48b7-bcac-2d8ae1b5c7a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contents_wrapper']/div[2]</value>
      <webElementGuid>33caa8b0-3ec7-46c0-b17f-854bfcbb2e94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout: Overview'])[1]/following::div[1]</value>
      <webElementGuid>bd8e88eb-14ff-4c3b-ae3e-e2d29365647a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Swag Labs'])[2]/following::div[3]</value>
      <webElementGuid>f29f5d64-491d-482a-85de-367495124948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]</value>
      <webElementGuid>7a734758-d9e9-4bd0-bc59-fa4a45d69722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'checkout_summary_container' and (text() = concat(&quot;QTYDescription1Sauce Labs Backpackcarry.allTheThings() with the sleek, streamlined Sly Pack that melds uncompromising style with unequaled laptop and tablet protection.$29.991Sauce Labs Fleece JacketIt&quot; , &quot;'&quot; , &quot;s not every day that you come across a midweight quarter-zip fleece jacket capable of handling everything from a relaxing day outdoors to a busy day at the office.$49.99Payment Information:SauceCard #31337Shipping Information:Free Pony Express Delivery!Price TotalItem total: $79.98Tax: $6.40Total: $86.38CancelFinish&quot;) or . = concat(&quot;QTYDescription1Sauce Labs Backpackcarry.allTheThings() with the sleek, streamlined Sly Pack that melds uncompromising style with unequaled laptop and tablet protection.$29.991Sauce Labs Fleece JacketIt&quot; , &quot;'&quot; , &quot;s not every day that you come across a midweight quarter-zip fleece jacket capable of handling everything from a relaxing day outdoors to a busy day at the office.$49.99Payment Information:SauceCard #31337Shipping Information:Free Pony Express Delivery!Price TotalItem total: $79.98Tax: $6.40Total: $86.38CancelFinish&quot;))]</value>
      <webElementGuid>40a92c8e-f8fd-4b38-890b-9591645930d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
